name: Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim-version: ['stable', 'nightly']
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Neovim
        uses: rhymond/setup-neovim@v1
        with:
          neovim-version: ${{ matrix.neovim-version }}
          
      - name: Install dependencies
        run: |
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim.git ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim
          
      - name: Run tests
        run: |
          nvim --headless --noplugin -u test/minimal_init.lua -c "PlenaryBustedDirectory test/ { minimal_init = 'test/minimal_init.lua' }"
          
      - name: Generate coverage
        if: matrix.neovim-version == 'stable'
        run: |
          # Coverage reporting setup
          echo "Coverage reporting would go here"

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install stylua
        run: |
          curl -L https://github.com/JohnnyMorganz/StyLua/releases/latest/download/stylua-linux.zip -o stylua.zip
          unzip stylua.zip
          chmod +x stylua
          sudo mv stylua /usr/local/bin/
          
      - name: Check formatting
        run: stylua --check lua/
        
      - name: Install luacheck
        run: |
          sudo apt-get update
          sudo apt-get install luarocks
          sudo luarocks install luacheck
          
      - name: Run luacheck
        run: luacheck lua/
